spring:
  datasource:
    url: jdbc:postgresql://db.exafcocghrrkvqiuudbc.supabase.co:5432/postgres
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true # 표준 출력이 아니라 로거로 확인하기 위해 아래 logging에 설정
        format_sql: true #sql format 예쁘게
        highlight_sql: true #sql 색칠해서
        use_sql_comments: true #주석으로 부가정보 더 표시
    open-in-view: true # 참고 OSIV https://livelyoneweek.tistory.com/57, https://velog.io/@dnwlsrla40/JPA-Open-In-View

logging:
  level:
    org:
      hibernate:
        SQL: debug # 표준 출력이 아니라 로거로 확인하려면 위 spring jpa properties가 아니라 여기 logging에 설정해야 한다.
        orm:
          jdbc:
            bind: trace #sql ? binding parameter까지 전부 확인하기
    springframework: # Security 적용 부분들을 체크하기 위한 로거
      security: debug

auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168
