drop table if exists review cascade;
drop table if exists comment cascade;
drop table if exists notice cascade;
drop table if exists app_user cascade;

create table review
(
    id                bigint generated by default as identity,
    created_at        timestamp(6) not null,
    last_modified_at  timestamp(6) not null,
    deleted_at        timestamp(6),
    user_id           bigint not null,
    store_name        varchar(40) not null,
    cuisine_category  varchar(20) not null,
    address           varchar(200) not null,
    visited_at        timestamp(6) not null,
    waiting_time      int not null,
    store_size        int not null,
    cleanliness       int not null,
    content           varchar(2000) not null,
    primary key (id)
);
create table comment
(
    id                bigint generated by default as identity,
    created_at        timestamp(6) not null,
    last_modified_at  timestamp(6) not null,
    deleted_at        timestamp(6),
    user_id           bigint not null,
    review_id         bigint not null,
    content           varchar(200) not null,
    primary key (id)
);
create table notice
(
    id                bigint generated by default as identity,
    created_at        timestamp(6) not null,
    last_modified_at  timestamp(6) not null,
    deleted_at        timestamp(6),
    user_id           bigint not null,
    title             varchar(100),
    content           varchar(2000),
    primary key (id)
);
create table app_user
(
    id                bigint generated by default as identity,
    created_at        timestamp(6) not null,
    last_modified_at  timestamp(6) not null,
    deleted_at        timestamp(6),
    username          varchar(10) not null,
    password          varchar(511) not null,
    email             varchar(50) not null,
    real_name         varchar(30) not null,
    nickname          varchar(30) not null,
    role              varchar(30) not null,
    introduction      varchar(200) not null,
    primary key (id)
);
create table invalidated_token
(
    id                bigint generated by default as identity,
    token             varchar(511) not null,
    primary key (id)
);
